services:
  # Group A Docker Daemons
  docker-daemon-a1:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    hostname: docker-daemon-a1
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - docker-network
    labels:
      - "group=a"

  docker-daemon-a2:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    hostname: docker-daemon-a2
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - docker-network
    labels:
      - "group=a"

  # Group B Docker Daemons
  docker-daemon-b1:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    hostname: docker-daemon-b1
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - docker-network
    labels:
      - "group=b"

  docker-daemon-b2:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    hostname: docker-daemon-b2
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - docker-network
    labels:
      - "group=b"

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "2375:2375"
    networks:
      - docker-network
    depends_on:
      docker-daemon-a1:
        condition: service_healthy
      docker-daemon-a2:
        condition: service_healthy
      docker-daemon-b1:
        condition: service_healthy
      docker-daemon-b2:
        condition: service_healthy

  sut:
    build: ./client
    environment:
      - DOCKER_HOST=http://haproxy:2375
    networks:
      - docker-network
    depends_on:
      - haproxy

networks:
  docker-network:
